23:20:55 - 来自: main.py:43 - <module>                          | 调用函数            | GameHelper.__init__                      | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>'}
23:20:55 - 来自: GameHelper.py:146 - __init__                   | 调用函数            | GameHelper.read_json                     | 参数: {}
23:20:55 - 来自: GameHelper.py:146 - __init__                   | 函数返回            | GameHelper.read_json                     | 返回值: {'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}
23:20:55 - 来自: GameHelper.py:163 - __init__                   | 调用函数            | GameHelper.write_json                    | 参数: {'data': "{'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}"}
23:20:55 - 来自: GameHelper.py:163 - __init__                   | 函数返回            | GameHelper.write_json                    | 返回值: None
23:20:55 - 来自: GameHelper.py:166 - __init__                   | 调用函数            | GameHelper.GetZoomRate                   | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>'}
23:20:55 - 来自: GameHelper.py:166 - __init__                   | 函数返回            | GameHelper.GetZoomRate                   | 返回值: None
23:20:55 - 来自: main.py:43 - <module>                          | 函数返回            | GameHelper.__init__                      | 返回值: None
23:20:55 - 来自: main.py:1289 - <module>                        | 调用函数            | __main__.__init__                        | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>'}
23:20:56 - 来自: main.py:1103 - __init__                        | 调用函数            | __main__.__init__                        | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
23:20:56 - 来自: main.py:1103 - __init__                        | 函数返回            | __main__.__init__                        | 返回值: None
23:20:56 - 来自: main.py:1104 - __init__                        | 调用函数            | __main__.init_info                       | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>'}
23:20:56 - 来自: main.py:1185 - init_info                       | 调用函数            | GameHelper.__init__                      | 参数: {'self': '<GameHelper.GameHelper object at 0x00000172C3D36D90>'}
23:20:56 - 来自: GameHelper.py:146 - __init__                   | 调用函数            | GameHelper.read_json                     | 参数: {}
23:20:56 - 来自: GameHelper.py:146 - __init__                   | 函数返回            | GameHelper.read_json                     | 返回值: {'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}
23:20:56 - 来自: GameHelper.py:163 - __init__                   | 调用函数            | GameHelper.write_json                    | 参数: {'data': "{'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}"}
23:20:56 - 来自: GameHelper.py:163 - __init__                   | 函数返回            | GameHelper.write_json                    | 返回值: None
23:20:56 - 来自: GameHelper.py:166 - __init__                   | 调用函数            | GameHelper.GetZoomRate                   | 参数: {'self': '<GameHelper.GameHelper object at 0x00000172C3D36D90>'}
23:20:56 - 来自: GameHelper.py:166 - __init__                   | 函数返回            | GameHelper.GetZoomRate                   | 返回值: None
23:20:56 - 来自: main.py:1185 - init_info                       | 函数返回            | GameHelper.__init__                      | 返回值: None
23:20:56 - 来自: main.py:1186 - init_info                       | 调用函数            | GameHelper.read_json                     | 参数: {}
23:20:56 - 来自: main.py:1186 - init_info                       | 函数返回            | GameHelper.read_json                     | 返回值: {'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}
23:20:56 - 来自: main.py:1104 - __init__                        | 函数返回            | __main__.init_info                       | 返回值: None
23:20:56 - 来自: main.py:1289 - <module>                        | 函数返回            | __main__.__init__                        | 返回值: None
01:42:22 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.auto_game                       | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': 'False'}
01:42:22 - 来自: main.py:1137 - auto_game                       | 调用函数            | GameHelper.__init__                      | 参数: {'self': '<GameHelper.GameHelper object at 0x00000172C5A184F0>'}
01:42:22 - 来自: GameHelper.py:146 - __init__                   | 调用函数            | GameHelper.read_json                     | 参数: {}
01:42:22 - 来自: 未知调用者                                          | 调用函数            | __main__.run                             | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:22 - 来自: main.py:242 - run                              | 调用函数            | __main__.init_datas                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:22 - 来自: GameHelper.py:146 - __init__                   | 函数返回            | GameHelper.read_json                     | 返回值: {'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}
01:42:22 - 来自: GameHelper.py:163 - __init__                   | 调用函数            | GameHelper.write_json                    | 参数: {'data': "{'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}"}
01:42:22 - 来自: GameHelper.py:163 - __init__                   | 函数返回            | GameHelper.write_json                    | 返回值: None
01:42:22 - 来自: GameHelper.py:166 - __init__                   | 调用函数            | GameHelper.GetZoomRate                   | 参数: {'self': '<GameHelper.GameHelper object at 0x00000172C5A184F0>'}
01:42:22 - 来自: GameHelper.py:166 - __init__                   | 函数返回            | GameHelper.GetZoomRate                   | 返回值: None
01:42:22 - 来自: main.py:277 - init_datas                       | 调用函数            | GameHelper.read_json                     | 参数: {}
01:42:22 - 来自: main.py:277 - init_datas                       | 函数返回            | GameHelper.read_json                     | 返回值: {'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}
01:42:22 - 来自: main.py:242 - run                              | 函数异常            | __main__.init_datas                      | 异常类型: KeyError | 异常信息: 'state' | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 279, in init_datas
    self.statement = data["state"]
KeyError: 'state'

01:42:22 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:22 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:22 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:22 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:23 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:23 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:23 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:23 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:23 - 来自: main.py:1137 - auto_game                       | 函数返回            | GameHelper.__init__                      | 返回值: None
01:42:23 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.auto_game                       | 返回值: None
01:42:23 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.init_interface                  | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '1'}
01:42:23 - 来自: main.py:1205 - init_interface                  | 调用函数            | __main__.recorder2zero                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>'}
01:42:23 - 来自: main.py:1205 - init_interface                  | 函数返回            | __main__.recorder2zero                   | 返回值: None
01:42:23 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.init_interface                  | 返回值: None
01:42:23 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.write_threshold                 | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '1'}
01:42:23 - 来自: main.py:1176 - write_threshold                 | 调用函数            | GameHelper.read_json                     | 参数: {}
01:42:23 - 来自: main.py:1176 - write_threshold                 | 函数返回            | GameHelper.read_json                     | 返回值: {'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}
01:42:23 - 来自: main.py:1181 - write_threshold                 | 调用函数            | GameHelper.write_json                    | 参数: {'data': "{'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}"}
01:42:23 - 来自: main.py:1181 - write_threshold                 | 函数返回            | GameHelper.write_json                    | 返回值: None
01:42:23 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.write_threshold                 | 返回值: None
01:42:23 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:23 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:25 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:25 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:25 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:25 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:25 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:25 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:25 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:25 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:25 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:25 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:27 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:27 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:27 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:27 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:27 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:27 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:27 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:27 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:27 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:27 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:29 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:29 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:29 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:29 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:29 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:29 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:29 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:29 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:29 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:29 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:31 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:31 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:31 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:31 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:31 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:31 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:31 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:31 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:31 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:31 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:33 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:33 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:33 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:33 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:33 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:33 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:33 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:33 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:33 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:33 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:35 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:35 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:35 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:35 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:35 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:35 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:35 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:35 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:35 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:35 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:37 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:37 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:37 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:37 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:37 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:37 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:37 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:37 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:37 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:37 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:39 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:39 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:39 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:39 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:39 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:39 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:39 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:39 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:39 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:39 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:41 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:41 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:41 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:41 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:41 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:41 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:41 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:41 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:41 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:41 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:43 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:43 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:43 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:43 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:43 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:43 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:43 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:43 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:43 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:43 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:44 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.auto_game                       | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': 'False'}
01:42:44 - 来自: main.py:1137 - auto_game                       | 调用函数            | GameHelper.__init__                      | 参数: {'self': '<GameHelper.GameHelper object at 0x00000172C5A0BC70>'}
01:42:44 - 来自: GameHelper.py:146 - __init__                   | 调用函数            | GameHelper.read_json                     | 参数: {}
01:42:44 - 来自: GameHelper.py:146 - __init__                   | 函数返回            | GameHelper.read_json                     | 返回值: {'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}
01:42:44 - 来自: GameHelper.py:163 - __init__                   | 调用函数            | GameHelper.write_json                    | 参数: {'data': "{'window': 1, 'bid1': '0.6', 'bid2': '0.6', 'bid3': '0.6', 'bid4': '0.6'}"}
01:42:44 - 来自: GameHelper.py:163 - __init__                   | 函数返回            | GameHelper.write_json                    | 返回值: None
01:42:44 - 来自: GameHelper.py:166 - __init__                   | 调用函数            | GameHelper.GetZoomRate                   | 参数: {'self': '<GameHelper.GameHelper object at 0x00000172C5A0BC70>'}
01:42:44 - 来自: GameHelper.py:166 - __init__                   | 函数返回            | GameHelper.GetZoomRate                   | 返回值: None
01:42:44 - 来自: main.py:1137 - auto_game                       | 函数返回            | GameHelper.__init__                      | 返回值: None
01:42:44 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.auto_game                       | 返回值: None
01:42:45 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:45 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:45 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:45 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:45 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:45 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:45 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:45 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:45 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:45 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:47 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:47 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:47 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:47 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:47 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:47 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:47 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:47 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:47 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:47 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:49 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:49 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:49 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:49 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:49 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:49 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:49 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:49 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:49 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:49 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:51 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:51 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:51 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:51 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:51 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:51 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:51 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:51 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:51 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:51 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:54 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:54 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:54 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:54 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:54 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:54 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:54 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:54 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:54 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:54 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:56 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:56 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:56 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:56 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:56 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:56 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:56 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:56 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:56 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:56 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:42:58 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:58 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:58 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:42:58 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:42:58 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:42:58 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:42:58 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:42:58 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:42:58 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:42:58 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:00 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:00 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:00 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:00 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:00 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:00 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:00 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:00 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:00 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:00 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:02 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:02 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:02 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:02 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:02 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:02 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:02 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:02 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:02 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:02 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:04 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:04 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:04 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:04 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:04 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:04 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:04 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:04 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:04 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:04 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:06 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:06 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:06 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:06 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:06 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:06 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:06 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:06 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:06 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:06 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:08 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:08 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:08 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:08 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:08 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:08 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:08 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:08 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:08 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:08 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:10 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:10 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:10 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:10 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:10 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:10 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:10 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:10 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:10 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:10 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:12 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:12 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:12 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:12 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:12 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:12 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:12 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:12 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:12 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:12 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:14 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:14 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:14 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:14 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:14 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:14 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:14 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:14 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:14 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:14 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:16 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:16 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:16 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:16 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:16 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:16 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:16 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:16 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:16 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:16 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:18 - 来自: main.py:260 - run                              | 调用函数            | __main__.before_start                    | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:18 - 来自: main.py:542 - before_start                     | 调用函数            | __main__.find_my_cards                   | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:18 - 来自: main.py:321 - find_my_cards                    | 调用函数            | GameHelper.Screenshot                    | 参数: {'self': '<GameHelper.GameHelper object at 0x0000017297BB5250>', 'region': 'None'}
01:43:18 - 来自: main.py:321 - find_my_cards                    | 函数异常            | GameHelper.Screenshot                    | 异常类型: error | 异常信息: (1400, 'GetWindowRect', '无效的窗口句柄。') | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\GameHelper.py", line 186, in Screenshot
    left, top, right, bot = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

01:43:18 - 来自: main.py:542 - before_start                     | 函数异常            | __main__.find_my_cards                   | 异常类型: error | 异常信息: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
 | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 322, in find_my_cards
    img = cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src data type = object is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'


01:43:18 - 来自: main.py:260 - run                              | 函数异常            | __main__.before_start                    | 异常类型: TypeError | 异常信息: argument of type 'NoneType' is not iterable | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 544, in before_start
    if "DX222" in self.user_hand_cards_real:
TypeError: argument of type 'NoneType' is not iterable

01:43:18 - 来自: main.py:261 - run                              | 调用函数            | __main__.init_cards                      | 参数: {'self': '<__main__.Worker object at 0x00000172C4073A60>'}
01:43:18 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.state_display                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '出牌前阶段'}
01:43:18 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.state_display                   | 返回值: None
01:43:18 - 来自: main.py:261 - run                              | 函数异常            | __main__.init_cards                      | 异常类型: TypeError | 异常信息: object of type 'NoneType' has no len() | 堆栈跟踪: Traceback (most recent call last):
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\log_utils.py", line 102, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\douzero项目汇总\测试用\5.8源码cursor版\main.py", line 695, in init_cards
    while len(self.three_cards_real) != 3:
TypeError: object of type 'NoneType' has no len()

01:43:19 - 来自: main.py:1291 - <module>                        | 调用函数            | __main__.stop                            | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': 'False'}
01:43:19 - 来自: main.py:1151 - stop                            | 调用函数            | __main__.init_interface                  | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>', 'result': '1'}
01:43:19 - 来自: main.py:1205 - init_interface                  | 调用函数            | __main__.recorder2zero                   | 参数: {'self': '<__main__.MaYun object at 0x00000172C3EB74C0>'}
01:43:19 - 来自: main.py:1205 - init_interface                  | 函数返回            | __main__.recorder2zero                   | 返回值: None
01:43:19 - 来自: main.py:1151 - stop                            | 函数返回            | __main__.init_interface                  | 返回值: None
01:43:19 - 来自: main.py:1291 - <module>                        | 函数返回            | __main__.stop                            | 返回值: None
